
import { Language } from './types';

export const TEXTS = {
  [Language.EN]: {
    title: "StyleMatch AI",
    subtitle: "Discover your perfect hairstyle and glasses with AI analysis.",
    uploadStep: "1. Upload Your Photos",
    frontView: "Front View",
    leftView: "Left Side",
    rightView: "Right Side",
    analyzeBtn: "Analyze Profile",
    analyzing: "Analyzing facial features...",
    generating: "Generating your new look...",
    resultsTitle: "Your Personal Analysis",
    faceShape: "Face Shape",
    skinTone: "Skin Tone",
    hairRec: "Recommended Hairstyles",
    glassesRec: "Recommended Glasses",
    selectPrompt: "Select styles to generate a new look.",
    generateBtn: "Generate Look",
    visualizeTitle: "Studio",
    reset: "Start Over",
    selectKey: "Connect Account",
    apiKeyNote: "Please connect your Google account to start the AI analysis and makeover generation.",
    uploadPlaceholder: "Click to upload",
    errorMissingImages: "Please upload all three images (Front, Left, and Right) to proceed.",
    billingLink: "Get API Key",
    selectOption: "Select",
    selected: "Selected",
    errorNoSelection: "Please select at least one hairstyle or glasses style.",
    history: "History",
    original: "Original",
    compareBtn: "Hold to Compare",
    look: "Look",
    emptyHistory: "Select options and click Generate to see results."
  },
  [Language.CN]: {
    title: "AI 造型顾问",
    subtitle: "通过 AI 分析您的面部特征，为您推荐最适合的发型与眼镜。",
    uploadStep: "1. 上传照片",
    frontView: "正面照",
    leftView: "左侧面",
    rightView: "右侧面",
    analyzeBtn: "开始面部分析",
    analyzing: "正在分析面部特征...",
    generating: "正在为您生成造型...",
    resultsTitle: "个人分析报告",
    faceShape: "脸型",
    skinTone: "肤色",
    hairRec: "推荐发型方案",
    glassesRec: "推荐眼镜方案",
    selectPrompt: "选择发型或眼镜，点击生成查看效果。",
    generateBtn: "生成造型",
    visualizeTitle: "造型工作室",
    reset: "重新开始",
    selectKey: "连接账户",
    apiKeyNote: "请连接您的 Google 账户以开始 AI 分析与造型生成。",
    uploadPlaceholder: "点击上传",
    errorMissingImages: "请上传所有三张照片（正面、左侧、右侧）以继续。",
    billingLink: "获取 API 密钥",
    selectOption: "选择",
    selected: "已选择",
    errorNoSelection: "请至少选择一种发型或眼镜款式。",
    history: "造型记录",
    original: "原始照片",
    compareBtn: "按住对比原图",
    look: "造型",
    emptyHistory: "请选择左侧方案并点击生成，预览效果将显示在此处。"
  }
};

export const PLACEHOLDER_AVATAR = "https://picsum.photos/300/300";
